[package]
name = "rust_for_java"
version = "0.1.0"
authors = ["fqliao <fqliao@yeah.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "rust_for_java"
crate-type = ["cdylib"]

[dependencies]
jni = "0.10.2"